services:
  elasticsearch:
    image: elasticsearch:8.0.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports: 
      - "9200:9200"
    healthcheck:
      test: "curl -sS http://localhost:9200 || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes: 
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic
    deploy:
      resources:
        limits:
          memory: 1g

  kibana:
    image: kibana:8.0.1
    container_name: kibana
    depends_on:
      - elasticsearch
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
      - "5601:5601"
    networks:
      - elastic

volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local

networks:
  elastic:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
